add "create with explicit ID" tests on field, fieldset, item, itemType, itemTypeFilters, menuItem, plugin, upload, uploadFilters and workflow
datocms/js-rest-api-clients pull request #16
Opened 2023-11-14 13:46 UTC by pinzer

2023-11-14 13:58 UTC, stefanoverna requested changes

2023-11-14 13:58 UTC, stefanoverna commented on packages/cma-client-node/__tests__/item.test.ts
> +    });
The client.items.bulkPublish here is not useful, is not part of what we want to test.

2023-11-14 14:03 UTC, pinzer commented on packages/cma-client-node/__tests__/item.test.ts
> +    });
correct, i will remove it, thanks

2023-11-14 18:24 UTC, sistrall reviewed
Tests don't run on CI because – I suppose – API PR about this feature is not released, yet. Am I correct?

2023-11-15 15:43 UTC, pinzer commented
> Tests don't run on CI because – I suppose – API PR about this feature is not released, yet. Am I correct?

correct, works on changes of the schema that are not yet in production

2023-11-20 12:14 UTC, merged